version: "2"

services:

  jenkins:
    build:
      context: .
    image: j
    user: jenkins
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ../config:/var/jenkins_home/mounted-configs/config
      - ../init.groovy.d:/var/jenkins_home/mounted-configs/init.groovy.d
      - ../job-dsl:/var/jenkins_home/mounted-configs/job-dsl
