---
- name: Deploy config files
  copy:
    src: ../jenkins/config
    dest: "{{ jenkins_home }}"

- name: copy Docker Compose files
  copy:
    src: ../jenkins/{{ item }}
    dest: "{{ jenkins_home }}/{{ item }}"
  loop:
    - docker-compose.yml
    - docker-compose.production.yml

- name: Start jenkins-master container
  docker_compose:
    project_src: "{{ jenkins_home }}"
    files:
      - docker-compose.yml
      - docker-compose.production.yml
  environment:
    GOOGLE_OAUTH_CLIENT_ID: "{{ GOOGLE_OAUTH_CLIENT_ID }}"
    GOOGLE_OAUTH_CLIENT_SECRET: "{{ GOOGLE_OAUTH_CLIENT_SECRET }}"
