---
- name: Deploy config files
  copy:
    src: ../jenkins-master-config/
    dest: "{{ mounted_configs }}"
  when:
    deploy_config
    
- name: Deploy Docker Compose files
  copy:
    src: ../jenkins-master-docker-compose/
    dest: "{{ jenkins_home }}/docker-compose"
  when:
    deploy_docker_compose

- name: Start jenkins-master container
  docker_compose:
    project_src: "{{ docker_compose_location }}"
    files: "{{ docker_compose_files }}"
  environment:
    "{{ docker_compose_environment_variables }}"
  when:
    start_container