---
- name: Deploy config files
  copy:
    src: ../jenkins-master-config/
    dest: "{{ mounted_configs }}"

- name: Start jenkins-master container
  docker_compose:
    project_src: "{{ mounted_configs }}/docker-compose"
    files:
      - docker-compose.yml
      - docker-compose.production.yml
  environment:
    GOOGLE_OAUTH_CLIENT_ID: "{{ GOOGLE_OAUTH_CLIENT_ID }}"
    GOOGLE_OAUTH_CLIENT_SECRET: "{{ GOOGLE_OAUTH_CLIENT_SECRET }}"
