controller:
  secondaryingress:
    enabled: true
    # Allow only incoming websocket connections
    paths: [ "/", "/wsagents/" ]

    annotations:
      # Use an internal HTTP(S) load balancer
      # Reference: https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balance-ingress
      kubernetes.io/ingress.class: "gce-internal"

      # Connect load balancer to a static IP address
      # The value of the 'undefined' parameter should be provided as an extra commandline argument when calling 'helm install'
      # Reference: https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balance-ingress#static_ip_addressing
      kubernetes.io/ingress.regional-static-ip-name: "undefined"
