- name: Setup docker host
  hosts: jenkins-master
  remote_user: ansible
  become: yes
  become_user: root

  roles:
    - role: angstwad.docker_ubuntu
      vars:
        ansible_python_interpreter: "{{ansible_playbook_python}}"
