- name: Install jenkins-master container
  hosts: jenkins-master
  remote_user: ansible
  become: yes
  become_user: root

  tasks:

    - name: Deploy config files
      copy:
        src: ../jenkins/config
        dest: /usr/jenkins_home/config

    - name: copy Docker Compose files
      copy:
        src: ../jenkins/{{ item }}
        dest: /usr/jenkins_home/{{ item }}
      loop:
        - docker-compose.yml
        - docker-compose.production.yml

    - name: Start jenkins-master container
      docker_compose:
        project_src: /usr/jenkins_home
        files:
          - docker-compose.yml
          - docker-compose.production.yml
