GOOGLE_OAUTH_CLIENT_ID: undefined
GOOGLE_OAUTH_CLIENT_SECRET: undefined

# Only used by GKE deploy
STATIC_IP_ADDRESS_NAME: undefined
IMAGE_TAG: undefined

SUBDOMAIN_NAME: undefined

controller:

  JCasC:
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false

    securityRealm: |-
      googleOAuth2:
        clientId: "{{ .Values.GOOGLE_OAUTH_CLIENT_ID }}"
        clientSecret: "{{ .Values.GOOGLE_OAUTH_CLIENT_SECRET }}"

    configScripts:
      # Add seed job
      seed-job: |
        jobs:
          - script: >
              job('Seed Job') {
                scm {
                  git {
                    remote {
                      url('${SEED_JOB_URL}')
                      credentials('github-user')
                    }
                    branch('*/main')
                  }
                }
                steps {
                  jobDsl {
                    targets "*.groovy"
                  }
                }
              }

      # Disable Script Security globally for Job DSL
      # In some sense this presents a potential security risk (any Job DSL code is trusted by default);
      #  the other options are to either run any Job DSL code in the Groovy Sandbox + whitelist any necessary functions,
      #  or to manually perform whitelisting of individual .groovy files from the seed job before running those scripts
      disable-script-security-for-job-dsl: |-
        security:
          globalJobDslSecurityConfiguration:
            useScriptSecurity: false

      # Add the UE_JENKINS_BUILDTOOLS_*_IMAGE OS-level environment variabls as job environment variable
      # This will be available in all jobs
      ue-jenkins-buildtools-images-env: |-
        jenkins:
          globalNodeProperties:
            - envVars:
                env:
                - key: "UE_JENKINS_BUILDTOOLS_LINUX_IMAGE"
                  value: "${UE_JENKINS_BUILDTOOLS_LINUX_IMAGE}"
                - key: "UE_JENKINS_BUILDTOOLS_WINDOWS_IMAGE"
                  value: "${UE_JENKINS_BUILDTOOLS_WINDOWS_IMAGE}"

      # Add timestamps to all job logs
      timestamper: |-
        unclassified:
          timestamper:
            allPipelines: true
            elapsedTimeFormat: "'<b>'HH:mm:ss.SSS'</b> '"
            systemTimeFormat: "'<b>'yyyy-MM-dd HH:mm:ss'</b> '"

# Enable the kubernetes-credentials-provider-plugin to read secrets
rbac:
  readSecrets: true

