version: "2"

services:

  jenkins:
    image: ${IMAGE_WITH_TAG}
    user: jenkins
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/mounts/config
      - JENKINS_URL=${JENKINS_URL}
    volumes:
      - ${HOST_MOUNTS}/init.groovy.d:/var/jenkins_home/mounts/init.groovy.d
      - ${HOST_MOUNTS}/job-dsl:/var/jenkins_home/mounts/job-dsl

