version: "2"

services:

  jenkins:
    build:
      context: .
    image: j
    user: jenkins
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    environment:
      - JENKINS_URL=${JENKINS_URL}
    volumes:
      - ../jenkins-master-config:/var/jenkins_home/mounted-configs
