version: "2"

services:

  jenkins:
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/mounted-configs/config/development
      - JENKINS_URL=http://localhost:8080/
      - JENKINS_ADMIN_USERNAME=admin
      - JENKINS_ADMIN_PASSWORD=smurf
  